"""initial

Revision ID: 6944838fe25d
Revises: 
Create Date: 2022-09-13 18:55:09.510202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6944838fe25d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('question_cgk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('answer', sa.ARRAY(sa.VARCHAR(length=32)), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nick', sa.VARCHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('capitan_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), nullable=True),
    sa.Column('start_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('bot_point', sa.Integer(), nullable=True),
    sa.Column('team_point', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['capitan_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_session_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('game_session_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), nullable=True),
    sa.Column('player_answer', sa.VARCHAR(length=32), nullable=True),
    sa.Column('respondent', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['game_session_id'], ['game_session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['question_cgk.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['respondent'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_models')
    op.drop_table('game_session_question')
    op.drop_table('game_session')
    op.drop_table('users')
    op.drop_table('question_cgk')
    op.drop_table('admins')
    # ### end Alembic commands ###
